version: latest

services:
  db:
    container_name: mysql_db
    image: mysql:latest
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - 3308:${DB_PORT}
    volumes:
      - data:/./mysql
    networks:
      - nova-oauth
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - data:/./redis
    networks:
      - nova-oauth

networks:
  nova-oauth:

volumes:
  data: